name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/60 * * * *'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "leeguoo@163.com"
          git config --local user.name "leeguooooo"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB }}@github.com/${{ github.repository }}
          git pull --rebase
          date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
          git commit -am "a commit a day keeps your girlfriend away"
          git push
